locations = {
	"birmingham" : "AL",
	"montgomery" : "AL",
	"huntsville" : "AL",
	"mobile" : "AL",
	"tuscaloosa" : "AL",
	"anchorage" : "AK",
	"fairbanks" : "AK",
	"juneau" : "AK",
	"sitka" : "AK",
	"ketchikan" : "AK",
	"phoenix" : "AZ",
	"tucson" : "AZ",
	"mesa" : "AZ",
	"chandler" : "AZ",
	"glendale" : "AZ",
	"little rock" : "AR",
	"fort smith" : "AR",
	"fayetteville" : "AR",
	"springdale" : "AR",
	"jonesboro" : "AR",
	"los angeles" : "CA",
	"san diego" : "CA",
	"san jose" : "CA",
	"san francisco" : "CA",
	"fresno" : "CA",
	"denver" : "CO",
	"colorado springs" : "CO",
	"aurora" : "CO",
	"fort collins" : "CO",
	"lakewood" : "CO",
	"bridgeport" : "CT",
	"new haven" : "CT",
	"stamford" : "CT",
	"hartford" : "CT",
	"waterbury" : "CT",
	"wilmington" : "DE",
	"dover" : "DE",
	"newark" : "DE",
	"middletown" : "DE",
	"smyrna" : "DE",
	"jacksonville" : "FL",
	"miami" : "FL",
	"tampa" : "FL",
	"orlando" : "FL",
	"st. petersburg" : "FL",
	"atlanta" : "GA",
	"columbus" : "GA",
	"augusta" : "GA",
	"macon" : "GA",
	"savannah" : "GA",
	"honolulu" : "HI",
	"hilo" : "HI",
	"kailua" : "HI",
	"kapolei" : "HI",
	"kaneohe" : "HI",
	"boise" : "ID",
	"meridian" : "ID",
	"nampa" : "ID",
	"idaho falls" : "ID",
	"pocatello" : "ID",
	"chicago" : "IL",
	"aurora" : "IL",
	"rockford" : "IL",
	"joliet" : "IL",
	"naperville" : "IL",
	"indianapolis" : "IN",
	"fort wayne" : "IN",
	"evansville" : "IN",
	"south bend" : "IN",
	"carmel" : "IN",
	"des moines" : "IA",
	"cedar rapids" : "IA",
	"davenport" : "IA",
	"sioux city" : "IA",
	"iowa city" : "IA",
	"wichita" : "KS",
	"overland park" : "KS",
	"kansas city" : "KS",
	"olathe" : "KS",
	"topeka" : "KS",
	"louisville" : "KY",
	"lexington" : "KY",
	"bowling green" : "KY",
	"owensboro" : "KY",
	"covington" : "KY",
	"new orleans" : "LA",
	"baton rouge" : "LA",
	"shreveport" : "LA",
	"lafayette" : "LA",
	"lake charles" : "LA",
	"portland" : "ME",
	"lewiston" : "ME",
	"bangor" : "ME",
	"south portland" : "ME",
	"auburn" : "ME",
	"baltimore" : "MD",
	"frederick" : "MD",
	"rockville" : "MD",
	"gaithersburg" : "MD",
	"bowie" : "MD",
	"boston" : "MA",
	"worcester" : "MA",
	"springfield" : "MA",
	"lowell" : "MA",
	"cambridge" : "MA",
	"detroit" : "MI",
	"grand rapids" : "MI",
	"warren" : "MI",
	"sterling heights" : "MI",
	"ann arbor" : "MI",
	"minneapolis" : "MN",
	"saint paul" : "MN",
	"rochester" : "MN",
	"bloomington" : "MN",
	"duluth" : "MN",
	"jackson" : "MS",
	"gulfport" : "MS",
	"southaven" : "MS",
	"hattiesburg" : "MS",
	"biloxi" : "MS",
	"kansas city" : "MO",
	"saint louis" : "MO",
	"springfield" : "MO",
	"independence" : "MO",
	"columbia" : "MO",
	"billings" : "MT",
	"missoula" : "MT",
	"great falls" : "MT",
	"bozeman" : "MT",
	"butte" : "MT",
	"omaha" : "NE",
	"lincoln" : "NE",
	"bellevue" : "NE",
	"grand island" : "NE",
	"kearney" : "NE",
	"las vegas" : "NV",
	"henderson" : "NV",
	"reno" : "NV",
	"north las vegas" : "NV",
	"sparks" : "NV",
	"manchester" : "NH",
	"nashua" : "NH",
	"concord" : "NH",
	"derry" : "NH",
	"rochester" : "NH",
	"newark" : "NJ",
	"jersey city" : "NJ",
	"paterson" : "NJ",
	"elizabeth" : "NJ",
	"edison" : "NJ",
	"albuquerque" : "NM",
	"las cruces" : "NM",
	"rio rancho" : "NM",
	"santa fe" : "NM",
	"roswell" : "NM",
	"new york city" : "NY",
	"buffalo" : "NY",
	"rochester" : "NY",
	"yonkers" : "NY",
	"syracuse" : "NY",
	"charlotte" : "NC",
	"raleigh" : "NC",
	"greensboro" : "NC",
	"durham" : "NC",
	"winston-salem" : "NC",
	"fargo" : "ND",
	"bismarck" : "ND",
	"grand forks" : "ND",
	"minot" : "ND",
	"west fargo" : "ND",
	"columbus" : "OH",
	"cleveland" : "OH",
	"cincinnati" : "OH",
	"toledo" : "OH",
	"akron" : "OH",
	"oklahoma city" : "OK",
	"tulsa" : "OK",
	"norman" : "OK",
	"broken arrow" : "OK",
	"lawton" : "OK",
	"portland" : "OR",
	"salem" : "OR",
	"eugene" : "OR",
	"gresham" : "OR",
	"hillsboro" : "OR",
	"philadelphia" : "PA",
	"pittsburgh" : "PA",
	"allentown" : "PA",
	"erie" : "PA",
	"reading" : "PA",
	"providence" : "RI",
	"warwick" : "RI",
	"cranston" : "RI",
	"pawtucket" : "RI",
	"east providence" : "RI",
	"charleston" : "SC",
	"columbia" : "SC",
	"north charleston" : "SC",
	"mount pleasant" : "SC",
	"rock hill" : "SC",
	"sioux falls" : "SD",
	"rapid city" : "SD",
	"aberdeen" : "SD",
	"brookings" : "SD",
	"watertown" : "SD",
	"nashville" : "TN",
	"memphis" : "TN",
	"knoxville" : "TN",
	"chattanooga" : "TN",
	"clarksville" : "TN",
	"houston" : "TX",
	"san antonio" : "TX",
	"dallas" : "TX",
	"austin" : "TX",
	"fort worth" : "TX",
	"salt lake city" : "UT",
	"west valley city" : "UT",
	"provo" : "UT",
	"west jordan" : "UT",
	"orem" : "UT",
	"burlington" : "VT",
	"essex" : "VT",
	"south burlington" : "VT",
	"rutland" : "VT",
	"barre" : "VT",
	"virginia beach" : "VA",
	"norfolk" : "VA",
	"chesapeake" : "VA",
	"richmond" : "VA",
	"newport news" : "VA",
	"seattle" : "WA",
	"spokane" : "WA",
	"tacoma" : "WA",
	"vancouver" : "WA",
	"bellevue" : "WA",
	"charleston" : "WV",
	"huntington" : "WV",
	"morgantown" : "WV",
	"parkersburg" : "WV",
	"wheeling" : "WV",
	"milwaukee" : "WI",
	"madison" : "WI",
	"green bay" : "WI",
	"kenosha" : "WI",
	"racine" : "WI",
	"cheyenne" : "WY",
	"casper" : "WY",
	"laramie" : "WY",
	"gillette" : "WY",
	"rock springs" : "WY",
	"alabama" : "AL",
	"alaska" : "AK",
	"arizona" : "AZ",
	"arkansas" : "AR",
	"california" : "CA",
	"colorado" : "CO",
	"connecticut" : "CT",
	"delaware" : "DE",
	"florida" : "FL",
	"georgia" : "GA",
	"hawaii" : "HI",
	"idaho" : "ID",
	"illinois" : "IL",
	"indiana" : "IN",
	"iowa" : "IA",
	"kansas" : "KS",
	"kentucky" : "KY",
	"louisiana" : "LA",
	"maine" : "ME",
	"maryland" : "MD",
	"massachusetts" : "MA",
	"michigan" : "MI",
	"minnesota" : "MN",
	"mississippi" : "MS",
	"missouri" : "MO",
	"montana" : "MT",
	"nebraska" : "NE",
	"nevada" : "NV",
	"new hampshire" : "NH",
	"new jersey" : "NJ",
	"new mexico" : "NM",
	"new york" : "NY",
	"north carolina" : "NC",
	"north dakota" : "ND",
	"ohio" : "OH",
	"oklahoma" : "OK",
	"oregon" : "OR",
	"pennsylvania" : "PA",
	"rhode island" : "RI",
	"south carolina" : "SC",
	"south dakota" : "SD",
	"tennessee" : "TN",
	"texas" : "TX",
	"utah" : "UT",
	"vermont" : "VT",
	"virginia" : "VA",
	"washington" : "WA",
	"west virginia" : "WV",
	"wisconsin" : "WI",
	"wyoming" : "WY"
}